/**
 * Cross-package mirror of backend `domain/audit/auditEventCatalog.ts` AUDIT_EVENT_CODES.
 * Append-only — never reorder. CI drift test keeps this in sync with domain.
 */
export const AUDIT_EVENT_CODES = [
  'auth.admin.login.success',
  'auth.admin.login.failed',
  'auth.admin.logout',
  'auth.admin.access.denied',
  'admin.invite.created',
  'admin.invite.resent',
  'admin.invite.activated',
  'admin.account.username_changed',
  'admin.account.password_changed',
  'admin.credentials.provider_secret.set',
  'admin.credentials.provider_secret.rotated',
  'admin.credentials.provider_secret.deleted',
  'admin.credentials.bank_secret.set',
  'admin.credentials.bank_secret.rotated',
  'admin.settings.updated',
  'admin.user.created',
  'admin.user.deactivated',
  'admin.user.reactivated',
  'admin.user.permanently_deleted',
  'admin.product.deactivated',
  'admin.product.reactivated',
  'admin.product.permanently_deleted',
  'admin.category.deactivated',
  'admin.category.reactivated',
  'admin.category.permanently_deleted',
  'admin.variant.archived',
  'admin.variant.restored',
  'admin.variant.permanently_deleted',
  'admin.pickupPoint.deactivated',
  'admin.pickupPoint.reactivated',
  'admin.pickupPoint.permanently_deleted',
  'admin.donationProject.deactivated',
  'admin.donationProject.reactivated',
  'admin.donationProject.archived',
  'admin.customerMembership.suspended',
  'admin.retention.policy_updated',
  'admin.salesPoint.deactivated',
  'admin.salesPoint.reactivated',
  'admin.salesPoint.permanently_deleted',
  'admin.tenant.deactivated',
  'admin.tenant.permanently_deleted',
  'admin.tenant.reactivated',
  'admin.donation_template.created',
  'admin.donation_template.updated',
  'admin.donation_template.default_set',
  'admin.salesPoint.donation_projects.updated',
  'admin.salesPoint.donation_amounts.updated',
  'admin.product.media_saved',
  'admin.product.media_deleted',
  'admin.product.primary_image_changed',
  'admin.loyalty.physical_card_issued',
  'admin.loyalty.physical_card_revoked',
  'admin.product.barcode_assigned',
  'admin.product.barcode_cleared',
  'admin.product.barcode_alt_added',
  'admin.product.barcode_alt_removed',
  'admin.product.barcode_alt_promoted',
  'pickup.device.paired',
  'pickup.device.pairing.failed',
  'pickup.fulfillment.claim.acquired',
  'pickup.fulfillment.claim.released',
  'dev.tenant.created',
  'dev.tenant.updated',
  'dev.tenant.provider.updated',
  'dev.tenant.entitlement_policy.changed',
  'payment.transaction.state_changed',
  'payment.admin_manual_complete',
  'payment.customer.refund.requested',
  'customer_pickup_ack_informational',
  'customer.receipt.downloaded',
  'reconciliation.transaction.refund_candidate.marked',
  'reconciliation.transaction.refund_candidate.unmarked',
  'reconciliation.bank_inbound.matched',
  'reconciliation.bank_inbound.attribute',
  'reconciliation.payment_claim.submitted',
  'reconciliation.payment_claim.approved',
  'reconciliation.payment_claim.rejected',
  'reconciliation.recurring_payment.missed',
  'reconciliation.recurring_payment.received',
  'reconciliation.bank_account.mode_changed',
  'payment.provider_wiring.verified',
  'payment.provider_wiring.verify_failed',
  'payment.provider_wiring.invalidated',
  'payment.cash_provider.risk_ack',
  'payment.cash_checkout.self_confirm',
  'payment.cash_shift.opened',
  'payment.cash_shift.closed',
  'payment.cash_drawer.open_signal',
  'export.analytics.explore.exported',
  'export.analytics.mission_control.exported',
  'analytics.mission_control.cross_tenant.read',
  'export.analytics.rollups.materialized',
  'export.transactions.exported',
  'export.fulfillment.exported',
  'export.compliance.audit_events.exported',
  'gdpr.erasure.completed',
  'gdpr.erasure.side_effects_pending',
] as const;

export type AuditEventCode = (typeof AUDIT_EVENT_CODES)[number];

const AUDIT_EVENT_CODE_SET: ReadonlySet<string> = new Set(AUDIT_EVENT_CODES);

export function isAuditEventCode(code: string): code is AuditEventCode {
  return AUDIT_EVENT_CODE_SET.has(code);
}
